"php-7.4":
  brew_name: "php@7.4"
  start: |
    {BREW_PATH}/opt/php@7.4/sbin/php-fpm -D -g {PID_FILE}
  stop: |
    pkill -F {PID_FILE}
  config_template: "php_fpm.conf.tmpl"

"php-7.3":
  brew_name: "php@7.3"
  start: |
    {BREW_PATH}/opt/php@7.3/sbin/php-fpm -D -g {PID_FILE}
  stop: |
    pkill -F {PID_FILE}
  config_template: "php_fpm.conf.tmpl"

"mysql-*":
  brew_name: "mariadb@10.6"
  start: |
    {BREW_PATH}/opt/mariadb@10.6/bin/mysql_install_db --defaults-file={CONF_FILE}
    {BREW_PATH}/opt/mariadb@10.6/bin/mysqld_safe --defaults-file={CONF_FILE} --nowatch --pid-file={PID_FILE} --init-file={APP_PATH}/conf/mariadb_init.txt
  stop: |
    pkill -F {PID_FILE}
  config_template: "mariadb.conf.tmpl"

"mariadb-*":
  brew_name: "mariadb@10.6"
  start: |
    {BREW_PATH}/opt/mariadb@10.6/bin/mysql_install_db --defaults-file={CONF_FILE}
    {BREW_PATH}/opt/mariadb@10.6/bin/mysqld_safe --defaults-file={CONF_FILE} --nowatch --pid-file={PID_FILE} --init-file={APP_PATH}/conf/mariadb_init.txt
  stop: |
    pkill -F {PID_FILE}
  config_template: "mariadb.conf.tmpl"

"redis-*":
  brew_name: "redis@6.2"
  start: |
    {BREW_PATH}/opt/redis/bin/redis-server {CONF_FILE}
  stop: |
    pkill -F {PID_FILE}
  config_template: "redis.conf.tmpl"