package core

const brewInstall = `
cd %s
curl -L https://github.com/Homebrew/brew/archive/refs/tags/3.3.6.tar.gz | tar xz --strip 1
echo "# Generated by pbrew" > ~/.zshrc
echo "bindkey '^[[H' beginning-of-line" >> ~/.zshrc
echo "bindkey '^[[F' end-of-line" >> ~/.zshrc
echo "bindkey '^[[3~' delete-char" >> ~/.zshrc
echo "bindkey '^[[A' history-beginning-search-backward" >> ~/.zshrc
echo "bindkey '^[[B' history-beginning-search-forward" >> ~/.zshrc
echo 'PROMPT="${PLATFORM_PROJECT}> "' >> ~/.zshrc
`
